name: Renovate

on:
  #schedule:
  #  - cron: "31 17 * * *"
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Only do a dry run'
        default: false
        required: false
        type: boolean
      repository:
        description: 'The repository to run on'
        required: false
        type: string
  workflow_call:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2.2.1
        with:
          private-key: ${{ secrets.RENOVATE_GITHUB_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.RENOVATE_GITHUB_APP_ID }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.2.0
        with:
          renovate-version: 42.64-full
          configurationFile: bot/config.json
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_DRY_RUN: ${{ inputs.dryRun && 'full' || null }}
          RENOVATE_REPOSITORIES: ${{ inputs.repository && format('["{0}"]', inputs.repository) || null }}
